- name: personal
  hosts: all
  vars_files:
      - secrets.yml
  tasks:
      - import_tasks: tasks/system.yml
        become: yes
        tags: system
      - import_tasks: tasks/packages.yml
        become: yes
        tags: [system, packages]
      - import_tasks: tasks/vim.yml
        become: no
        tags: [home, vim]
      - import_tasks: tasks/zsh.yml
        become: no
        tags: [home, zsh]
      - import_tasks: tasks/rbenv.yml
        become: no
        tags: [home, rbenv]
      - name: "copy .autoprojrc"
        become: no
        tags: home
        copy:
            src: files/home/.autoprojrc
            dest: "/home/{{ username }}/.autoprojrc"
            owner: "{{ username }}"
            mode: 0644

