- name: personal
  hosts: all
  become: true
  vars_files:
      - secrets.yml
  tasks:
      - name: "Install APT keys for the non-PPA repositories"
        apt_key:
            keyserver: keyserver.ubuntu.com
            id: "{{ item }}"
            state: present
        with_items:
            - "0xA87FF9DF48BF1C90" # spotify

      - name: "Install APT repositories"
        apt_repository:
            repo: "{{ item }}"
            state: present
        with_items:
            - ppa:pmjdebruijn/darktable-release
            - deb http://repository.spotify.com stable non-free
            - deb [arch=amd64] http://repo.steampowered.com/steam/ precise steam
  
      - name: "Run apt-get update"
        apt:
            update_cache: yes
  
      - name: "Install packages"
        apt:
            name: "{{ packages }}"
        vars:
            packages:
                - darktable
                - digikam
                - kdenlive
  
      - name: "copy .autoprojrc"
        copy:
            src: files/home/.autoprojrc
            dest: "/home/{{ username }}/.autoprojrc"
            owner: "{{ username }}"
            mode: 0644

      - name: "Ensure bcache is always properly setup"
        copy:
            src: files/etc/udev/rules.d/10-bcache.rules
            dest: /etc/udev/rules.d/10-bcache.rules
            owner: root
            mode: 0644

      - name: "Setup auto-mounting Diskstation when at home"
        template:
            src: files/etc/NetworkManager/dispatcher.d/99-mount-photos.j2
            dest: /etc/NetworkManager/dispatcher.d/99-mount-photos
            owner: root
            group: root
            mode: 0700

      - name: "Setup auto-unmounting Diskstation when not at home"
        copy:
            src: files/etc/NetworkManager/dispatcher.d/pre-down.d/99-umount-photos
            dest: /etc/NetworkManager/dispatcher.d/pre-down.d/99-umount-photos
            owner: root
            mode: 0700

      - name: "Copy our skypeforlinux wrapper to use echo cancellation in PulseAudio"
        copy:
            src: files/usr/local/bin/skypeforlinux
            dest: /usr/local/bin/skypeforlinux
            owner: root
            mode: 0755

