- name: "Install APT keys for the non-PPA repositories"
  apt_key:
      keyserver: keyserver.ubuntu.com
      id: "{{ item }}"
      state: present
  with_items:
      - "0xA87FF9DF48BF1C90" # spotify
      - "F24AEA9FB05498B7" # steam

- name: "Install APT repositories"
  apt_repository:
      repo: "{{ item }}"
      state: present
  with_items:
      - ppa:pmjdebruijn/darktable-release
      - deb http://repository.spotify.com stable non-free
      - deb [arch=amd64] http://repo.steampowered.com/steam/ precise steam

- name: "Run apt-get update"
  apt:
      update_cache: yes

- name: "Install packages"
  apt:
      name: "{{ packages }}"
  vars:
      packages:
          - darktable
          - digikam
          - kdenlive
          - vim
          - spotify-client
          - zsh


