#!/bin/sh -e

PREREQS="udev"

prereqs() { echo "$PREREQS"; }

case "$1" in
    prereqs)
    prereqs
    exit 0
    ;;
esac

test -f files/etc/initramfs-tools/scripts/init-top/udev-late
echo $?

udevadm trigger
while ! test -f /dev/bcache0; do
    sleep 1
    udevadm trigger
done
